version: '3.8'
services:
  db:
    image: postgres:15-alpine
    container_name: crm_vehiculos_db
    environment:
      - POSTGRES_DB=crm_db
      - POSTGRES_USER=crm_user
      - POSTGRES_PASSWORD=crm_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    container_name: crm_vehiculos_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8001:8000"
    environment:
      - DB_NAME=crm_db
      - DB_USER=crm_user
      - DB_PASSWORD=crm_password
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db

volumes:
  postgres_data: