# Generated by Django 4.2.30 on 2026-08-08 21:56

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('V', 'Venezolano'), ('E', 'Extranjero'), ('J', 'Jurídico'), ('G', 'Gubernamental')], default='V', max_length=1)),
                ('identificacion', models.CharField(max_length=15, unique=True, verbose_name='Cédula/RIF')),
                ('nombre_razon_social', models.CharField(max_length=150)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('B', 'Borrador'), ('E', 'Emitida'), ('F', 'Facturada'), ('A', 'Anulada')], default='B', max_length=1)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('monto_exento', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('base_imponible', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('impuesto_iva', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='cotizaciones', to='facturacion.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('placa', models.CharField(blank=True, max_length=20, null=True)),
                ('anio', models.IntegerField(verbose_name='Año')),
                ('clase', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
                ('uso', models.CharField(max_length=50)),
                ('transmision', models.CharField(max_length=50)),
                ('tipo_combustible', models.CharField(max_length=50)),
                ('num_puestos', models.IntegerField(verbose_name='N° de Puestos')),
                ('num_ejes', models.IntegerField(verbose_name='N° de Ejes')),
                ('peso_tara', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Peso (Tara)')),
                ('capacidad_carga', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Capacidad de Carga (KG)')),
                ('serial_motor', models.CharField(max_length=100, verbose_name='Serial Motor')),
                ('serial_carroceria_niv', models.CharField(max_length=150, verbose_name='Serial Carrocería y NIV')),
                ('certificado_origen', models.CharField(blank=True, max_length=100, null=True, verbose_name='Certificado de Origen')),
                ('servicio', models.CharField(blank=True, max_length=50, null=True)),
                ('puerto_entrada', models.CharField(blank=True, max_length=100, null=True, verbose_name='Puerto de Entrada')),
                ('fecha_liquidacion', models.DateField(blank=True, null=True, verbose_name='Fecha de Liquidación')),
                ('planilla_liquidacion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Planilla de Liquidación')),
                ('fecha_facturacion', models.DateField(blank=True, null=True, verbose_name='Fecha de Facturación')),
                ('factura_adquisicion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Factura de Adquisición')),
                ('refeciv', models.CharField(blank=True, max_length=100, null=True, verbose_name='REFECIV')),
                ('fecha_fin_convenio', models.DateField(blank=True, null=True, verbose_name='Fecha Fin del Convenio')),
            ],
        ),
        migrations.CreateModel(
            name='ItemCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=15)),
                ('aplica_iva', models.BooleanField(default=True)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='facturacion.cotizacion')),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='facturacion.vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(max_length=20, unique=True)),
                ('numero_control', models.CharField(max_length=20, unique=True)),
                ('fecha_emision', models.DateField()),
                ('monto_exento', models.DecimalField(decimal_places=2, max_digits=15)),
                ('base_imponible', models.DecimalField(decimal_places=2, max_digits=15)),
                ('impuesto_iva', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cotizacion', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='factura', to='facturacion.cotizacion')),
            ],
        ),
    ]
