# Generated by Django 4.2.30 on 2026-08-07 15:58

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotizacion',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='vehiculo',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='igtf_percibido',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='kilometraje',
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='base_imponible',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='cotizaciones', to='facturacion.cliente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='monto_exento',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AddField(
            model_name='factura',
            name='base_imponible',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='factura',
            name='monto_exento',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemcotizacion',
            name='vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='facturacion.vehiculo'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='capacidad_carga',
            field=models.PositiveIntegerField(blank=True, help_text='Capacidad en KG', null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='clase',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='num_ejes',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='num_puestos',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='peso_tara',
            field=models.PositiveIntegerField(blank=True, help_text='Peso en KG', null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='serial_carroceria',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='serial_motor',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='serial_niv',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='serie_version',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='tipo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='tipo_combustible',
            field=models.CharField(default='GASOLINA', max_length=20),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='transmision',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='uso',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='impuesto_iva',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='factura',
            name='impuesto_iva',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='factura',
            name='numero_control',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='numero_factura',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='itemcotizacion',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='color',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='placa',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
