# Generated by Django 4.2.30 on 2026-08-17 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0002_cotizacion_usuario_factura_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='coletillas',
            field=models.TextField(blank=True, default='1. Esta factura se emite sin tachaduras ni enmendaduras.\n2. Los pagos deben realizarse a nombre de EMVEPRO.', null=True, verbose_name='Coletillas y Condiciones'),
        ),
    ]
