# Generated by Django 4.2.30 on 2026-08-19 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0003_factura_coletillas'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='tasa_cambio',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Tasa oficial del BCV al momento de emitir la factura', max_digits=10, verbose_name='Tasa de Cambio (Bs.)'),
        ),
    ]
